version: "3.1"
services:
  db: 
    image: postgres
    restart: always    
    environment:
      POSTGRES_DB: purebadesarrolloback
      POSTGRES_USER: dierick
      POSTGRES_PASSWORD: dierick    
    volumes:
    - ./pgdata:/var/lib/postgresql/data   
    ports:
      - "5432:5432"
  web:
    image: stripe-example-multi-stage
    restart: always
    depends_on:
      - db
    ports:
      - "4000:4000"  