version: "3.6"
services:
  app:
    build: .
    ports:
      - 3001:3001
    env_file: .env
    depends_on:
      - db
  db: 
    image: postgres
    restart: always    
    environment:
      POSTGRES_DB: typeormdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dierick
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgressql/data
volumes: 
  db-data:
      
      